// src/templates/vue/javascript/webpack/src/App.vue
<script setup>
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <div class="flex min-h-screen flex-col items-center justify-center">
    <h1 class="text-4xl font-bold"><%= projectName %></h1>
    <div class="mt-8">
      <button 
        class="rounded bg-blue-500 px-4 py-2 text-white hover:bg-blue-600"
        @click="count++"
      >
        count is {{ count }}
      </button>
    </div>
  </div>
</template>

// src/templates/react/javascript/webpack/src/App.jsx
import { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="flex min-h-screen flex-col items-center justify-center">
      <h1 className="text-4xl font-bold"><%= projectName %></h1>
      <div className="mt-8">
        <button 
          className="rounded bg-blue-500 px-4 py-2 text-white hover:bg-blue-600"
          onClick={() => setCount(count => count + 1)}
        >
          count is {count}
        </button>
      </div>
    </div>
  )
}

export default App
